import Link from 'next/link'
import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Web3 from 'web3'
import { formatDate, formatValue } from '@/utils'


export async function getServerSideProps(
  context: any
): Promise<{ props: { tx: any } }> {
  const { query } = context
  const { hash } = query

  const web3 = new Web3('https://mainnet.infura.io/v3/aa9dd50ea9bf4dec9fa7688f10a3c5db')

  const data = await web3.eth.getTransaction(hash)
  const block = await web3.eth.getBlock(data.blockNumber || 0)
  const receipt = await web3.eth.getTransactionReceipt(hash)

  return {
    props: {
      tx: {
        data,
        block,
        receipt
      }
    }
  };
}

export default function Tx({ tx }: { tx: any }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={`${styles.description} ${styles.center} mb-2`}>
          <div>
            <div className='mb-2'>
              <div className='mb-2'>
                <h4>Hash</h4>
                <Link
                  href={`https://etherscan.io/tx/${tx.data.hash}`}
                  target='_blank'
                >
                  <p>
                    {tx.data.hash}
                  </p>
                </Link>
              </div>
              <div className='mb-2'>
                <h4>Timestamp</h4>
                <p>
                  {formatDate(tx.block.timestamp)}
                </p>
              </div>
              <div className='mb-2'>
                <h4>Value</h4>
                <p>
                  {formatValue(tx.data.value)}
                </p>
              </div>
              <div className='mb-2'>
                <h4>Status</h4>
                <p>
                  {tx.receipt.status ? 'Confirmed' : 'Pending'}
                </p>
              </div>
              <div className='mb-2'>
                <h4>Fee</h4>
                <p>
                  {formatValue(tx.receipt.gasUsed * tx.receipt.effectiveGasPrice, 6)} ETH
                </p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
