import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Header from './Header'
import TxTable from './TxTable'
import Web3 from 'web3'
import { formatValue } from '@/utils'


type Data = {
  balance: string
  txs: any[]
}

async function getBalance(address: string) {
  const web3 = new Web3('https://mainnet.infura.io/v3/aa9dd50ea9bf4dec9fa7688f10a3c5db')
  const balanceInWei = await web3.eth.getBalance(address)
  return formatValue(balanceInWei)
}

async function getTxs(address: string) {
  const apiUrl = `https://api.etherscan.io/api?module=account&action=txlist&address=${address}&page=1&offset=100&sort=desc&apikey=9HEINRFRXD39GP6V3FY54A9Q97XWBI6WWG`;
  const txRes = await fetch(apiUrl)
  return (await txRes.json()).result
}

export async function getServerSideProps(
  context: any
): Promise<{ props: Data }> {
  const { query } = context
  const { address } = query

  return {
    props: {
      balance: await getBalance(address),
      txs: await getTxs(address),
    }
  };
}

export default function Address({ balance, txs }: Data) {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header balance={balance} />
        <TxTable txs={txs} />
      </main>
    </>
  )
}
